# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  github-minvws:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{ secrets.REPO_READ_ONLY_TOKEN }}"

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directories:
      - "/application-api"
      - "/application-backend"
      - "/shared"
      - "/assessment-api"
      - "/subsidy-admin-api"
      - "/user-admin-api"
      - "/bridge"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    registries:
      - github-minvws

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directories:
      - "/application-api"
      - "/application-backend"
      - "/shared"
      - "/assessment-api"
      - "/subsidy-admin-api"
      - "/user-admin-api"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    registries:
      - github-minvws
