UPDATE public.fields
SET params = '{"readonly": true, "deadlineSource": "field", "deadlineAdditionalPeriod": "P48W", "deadlineSourceFieldReference": {"stage": 1, "fieldCode": "abroadCourseComponentStartDate"}, "deadlineOverrideFieldReference": {"stage": 2, "fieldCode": "assignationDeadlineOverride"}}'
WHERE subsidy_stage_id = '7075fcad-7d92-42f6-b46c-7733869019e0'
  AND code = 'assignationDeadline';

INSERT INTO public.fields (id, title, description, type, params, is_required, code, source, subsidy_stage_id, required_condition, retention_period_on_approval, exclude_from_clone_data) VALUES ('4b6a73b7-a2a0-4bb2-bfb8-5e9bf23f1c51', 'Overschrijf vaststellings deadline', null, 'date', 'null', false, 'assignationDeadlineOverride', 'user', '59ddbc42-8ffc-4e2c-a751-d937714b6df6', null, 'short', true);
INSERT INTO public.fields (id, title, description, type, params, is_required, code, source, subsidy_stage_id, required_condition, retention_period_on_approval, exclude_from_clone_data) VALUES ('a446b318-1199-45fa-92ec-2e1e11378597', 'Vaststellings deadline', null, 'date', '{"readonly": true, "deadlineSource": "now", "deadlineAdditionalPeriod": "P1Y", "deadlineOverrideFieldReference": {"stage": 5, "fieldCode": "assignationDeadlineOverride"}}', false, 'assignationDeadline', 'calculated', '59ddbc42-8ffc-4e2c-a751-d937714b6df6', '{"type": "comparison", "stage": 5, "value": "Uitstellen", "operator": "===", "fieldCode": "assessment"}', 'short', true);

INSERT INTO public.fields (id, title, description, type, params, is_required, code, source, subsidy_stage_id, required_condition, retention_period_on_approval, exclude_from_clone_data) VALUES ('f706f15e-6fff-4169-b406-974d40db8120', 'Overschrijf vaststellings deadline', null, 'date', 'null', false, 'assignationDeadlineOverride', 'user', '2b06aee1-ea36-41a4-b7ae-74fa53c64a64', null, 'short', true);
INSERT INTO public.fields (id, title, description, type, params, is_required, code, source, subsidy_stage_id, required_condition, retention_period_on_approval, exclude_from_clone_data) VALUES ('6085a9ae-178c-44e3-a85a-7d1e983d68ab', 'Vaststellings deadline', null, 'date', '{"readonly": true, "deadlineSource": "now", "deadlineAdditionalPeriod": "P1Y", "deadlineOverrideFieldReference": {"stage": 6, "fieldCode": "assignationDeadlineOverride"}}', false, 'assignationDeadline', 'calculated', '2b06aee1-ea36-41a4-b7ae-74fa53c64a64', '{"type": "comparison", "stage": 6, "value": "Uitstellen", "operator": "===", "fieldCode": "assessment"}', 'short', true);

UPDATE public.subsidy_stage_transitions
SET target_application_review_deadline_source = 'field',
    target_application_review_deadline_source_field = '{"stage": 5, "fieldCode": "assignationDeadline"}'
WHERE id = 'd63ae140-2470-45de-a57e-8c58cf34b287';

UPDATE public.subsidy_stage_transitions
SET target_application_review_deadline_source = 'field',
    target_application_review_deadline_source_field = '{"stage": 6, "fieldCode": "assignationDeadline"}'
WHERE id = '90b1bab7-ed8d-4609-b669-0b771f325432';

UPDATE public.subsidy_stage_uis
SET input_ui = '{"type":"FormGroupControl","options":{"section":true,"group":true},"elements":[{"type":"Group","label":"Beoordeling","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assignationAssessmentChecklist","options":{"format":"checkbox-group"}}]}]},{"type":"Group","label":"Status","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assessment","options":{"format":"radio"}}]}]},{"type":"Group","label":"Deadline","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assignationDeadlineOverride","options":{"placeholder":"","remoteAction":["onBlur"]}}]},{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assignationDeadline","options":{"readonly":true}}]}],"rule":{"effect":"SHOW","condition":{"scope":"#\/properties\/assessment","schema":{"const":"Uitstellen"}}}},{"type":"Group","label":"Toelichting","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/proof","label":"Bewijs","options":{"accept":"image\/jpeg,image\/png,application\/pdf","maxFileSize":20971520,"minItems":1,"maxItems":20,"tip":"Upload een of meerdere bewijsstukken. Toegestane bestandstypen: pdf, jpg, jpeg, png. Maximale bestandsgrootte: 20 MB."}},{"type":"CustomControl","scope":"#\/properties\/internalNote","options":{"format":"textarea"}}]}]}]}',
    view_ui = '{"type":"FormGroupControl","options":{"section":true},"elements":[{"type":"CustomControl","scope":"#\/properties\/assignationAssessmentChecklist","options":{"readonly":true,"format":"checkbox-group"}},{"type":"CustomControl","scope":"#\/properties\/assessment","options":{"readonly":true,"format":"radio"}},{"type":"CustomControl","scope":"#\/properties\/assignationDeadlineOverride","options":{"readonly":true},"rule":{"effect":"SHOW","condition":{"scope":"#\/properties\/assessment","schema":{"const":"Uitstellen"}}}},{"type":"CustomControl","scope":"#\/properties\/assignationDeadline","options":{"readonly":true},"rule":{"effect":"SHOW","condition":{"scope":"#\/properties\/assessment","schema":{"const":"Uitstellen"}}}},{"type":"FormResultsTable","options":{"fields":{"Bewijs":"{proof}","Interne notitie":"{internalNote}"},"showEmptyFields":true}}]}'
WHERE id = '6b9e3359-8c44-4bfd-a593-baa5c4b8d19d';

UPDATE public.subsidy_stage_uis
SET input_ui = '{"type":"FormGroupControl","options":{"section":true,"group":true},"elements":[{"type":"Group","label":"Beoordeling","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assignationAssessmentChecklist","options":{"format":"checkbox-group"}}]}]},{"type":"Group","label":"Status","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assessment","options":{"format":"radio"}}]}]},{"type":"Group","label":"Deadline","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assignationDeadlineOverride","options":{"placeholder":"","remoteAction":["onBlur"]}}]},{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/assignationDeadline","options":{"readonly":true}}]}],"rule":{"effect":"SHOW","condition":{"scope":"#\/properties\/assessment","schema":{"const":"Uitstellen"}}}},{"type":"Group","label":"Toelichting","elements":[{"type":"VerticalLayout","elements":[{"type":"CustomControl","scope":"#\/properties\/proof","label":"Bewijs","options":{"accept":"image\/jpeg,image\/png,application\/pdf","maxFileSize":20971520,"minItems":1,"maxItems":20,"tip":"Upload een of meerdere bewijsstukken. Toegestane bestandstypen: pdf, jpg, jpeg, png. Maximale bestandsgrootte: 20 MB."}},{"type":"CustomControl","scope":"#\/properties\/internalNote","options":{"format":"textarea"}}]}]}]}',
    view_ui = '{"type":"FormGroupControl","options":{"section":true},"elements":[{"type":"CustomControl","scope":"#\/properties\/assignationAssessmentChecklist","options":{"readonly":true,"format":"checkbox-group"}},{"type":"CustomControl","scope":"#\/properties\/assessment","options":{"readonly":true,"format":"radio"}},{"type":"CustomControl","scope":"#\/properties\/assignationDeadlineOverride","options":{"readonly":true},"rule":{"effect":"SHOW","condition":{"scope":"#\/properties\/assessment","schema":{"const":"Uitstellen"}}}},{"type":"CustomControl","scope":"#\/properties\/assignationDeadline","options":{"readonly":true},"rule":{"effect":"SHOW","condition":{"scope":"#\/properties\/assessment","schema":{"const":"Uitstellen"}}}},{"type":"FormResultsTable","options":{"fields":{"Bewijs":"{proof}","Interne notitie":"{internalNote}"},"showEmptyFields":true}}]}'
WHERE id = '2a227775-700d-4f59-9322-900bb326afff';
