version: '3.9'

services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - '../application-model:/var/www/application-model'
            - '../subsidy-model:/var/www/subsidy-model'
            - '../serialisation-model:/var/www/serialisation-model'
            - '../bridge:/var/www/bridge'
        networks:
            portal-web:
            portal-backend:
            form-admin-web:

networks:
    portal-web:
    portal-backend:
        name: portal-backend
        external: true
    form-admin-web:
        name: form-admin-web
        external: true
