name: Generate Documentation - Handleiding

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest

    name: create manual documentation (pdf)

    strategy:
      matrix:
        include:
          - name: "Gebruikersbeheer - handleiding"
            directory: user-admin-api
          - name: "Beoordelingsportaal - handleiding"
            directory: assessment-api
          - name: "Helpdesk gebruikers - handleiding"
            directory: application-api
          - name: "Formulierbeheer - handleiding"
            directory: subsidy-admin-api

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set release version
        run: echo "RELEASE_VERSION=proof" >> $GITHUB_ENV

      - name: Set env
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "${{ matrix.directory }}/doc/manual/*.md"

      - name: Concat manual files
        if: steps.check_files.outputs.files_exists == 'true'
        uses: bayssmekanique/action-md-concat@v1
        with:
          srcDir: ${{ matrix.directory }}/doc/manual
          destFile: "${{ matrix.directory }}/doc/${{ matrix.name }} ${{ env.RELEASE_VERSION }}.md"

      - name: Publish document
        if: steps.check_files.outputs.files_exists == 'true'
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: "${{ matrix.directory }}/doc/${{ matrix.name }}.md"
          images_dir: ${{ matrix.directory }}/doc/manual/images
          output_dir: pdfs
          # for example <img src="./images/file-name.png">
          image_import: ./images
          build_html: false
          table_of_contents: true
          template: .github/workflows/manual/pdf_template.html
          theme: .github/workflows/manual/manon-sky-blue.css
         
      - name: Upload manual documentation (pdf)
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v3
        id: upload-document
        with:
          name: handleidingen
          path: pdfs
