name: Generate Documentation - Handleiding

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest

    name: create manual documentation (pdf)

    strategy:
      matrix:
        directory: ["user-admin-api", "subsidy-admin-api", "application-backend", "application-api", "assessment-api"]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "${{ matrix.directory }}/doc/manual/*.md"

      - name: contact-manual-files
        if: steps.check_files.outputs.files_exists == 'true'
        uses: bayssmekanique/action-md-concat@v1
        with:
          srcDir: ${{ matrix.directory }}/doc/manual
          destFile: ${{ matrix.directory }}/doc/manual.md

      - name: publish-document
        if: steps.check_files.outputs.files_exists == 'true'
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ${{ matrix.directory }}/doc/manual.md
          images_dir: ${{ matrix.directory }}/doc/manual/images
          output_dir: pdfs
          # for example <img src="./images/file-name.png">
          image_import: ./images
          build_html: false
          table_of_contents: true
          template: .github/workflows/pdf_template.html
          theme: .github/workflows/manon-sky-blue.css
         
      - name: upload manual documentation (pdf)
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'handleiding-dusi'
          path: pdfs