name: npm

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

env:
  NODE_VERSION: 20

jobs:
  install-and-build:
    name: 'Install & Build'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        directory: ["shared", "user-admin-api"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.directory }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ matrix.directory }}/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'

      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

      - run: npm run build
        
      - run: npm audit
