name: PHP Linting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  call-composer-install:
    uses: ./.github/workflows/composer-install.yml
    secrets:
      REPO_READ_ONLY_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}
  
  php-linting-psalm:
    needs: call-composer-install
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Generate _ide_helper file
        run: php artisan ide-helper:generate
      - name: Static analysis with Psalm
        run: vendor/bin/psalm

  php-linting-psr12:
    needs: call-composer-install
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Coding style PSR12 Check
        run: vendor/bin/phpcs

  php-linting-stan:
    needs: call-composer-install
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Static analysis with PHPStan
        run: vendor/bin/phpstan analyse

  php-linting-cve:
    needs: call-composer-install
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Check for known CVE vulnerabilities
        run: php artisan security-check:now
