name: PHP Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.sh'

  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '**/*.sh'

jobs:
  call-composer-install:
    uses: ./.github/workflows/composer-install.yml
    secrets:
      REPO_READ_ONLY_TOKEN: ${{ secrets.REPO_READ_ONLY_TOKEN }}

  php-tests:
    strategy:
      matrix:
        directory: ["shared", "user-admin-api", "subsidy-admin-api", "application-backend", "application-api", "assessment-api"]

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    needs:
      - call-composer-install
    runs-on: ubuntu-20.04

    services:
      postgres-1:
        image: postgres:12.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: portal_backend_testing
        ports:
          - 54322:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres-2:
        image: postgres:12.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: user_testing
        ports:
          - 54323:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: pcov
          extensions: xdebug, pgsql

      - name: Copy .env
        continue-on-error: true
        run: cp -n .env.example .env

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.directory }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.directory }}-composer-

      - name: Install Dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.REPO_READ_ONLY_TOKEN }}"}}'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        continue-on-error: true
        run: php artisan key:generate

      - name: Generate Public Key
        run: |
          mkdir -p 'secrets'
          openssl genpkey -algorithm RSA -out 'secrets/private.key'
          openssl rsa -pubout -in 'secrets/private.key' -out 'secrets/public.key'

      - name: Execute tests with Code Coverage
        env:
          DB_APPLICATION_HOST: localhost
          DB_APPLICATION_DATABASE: portal_backend_testing
          DB_APPLICATION_PORT: 54322
          DB_APPLICATION_USERNAME: postgres
          DB_APPLICATION_PASSWORD: password
          DB_APPLICATION_SSLMODE: prefer
          DB_USER_HOST: localhost
          DB_USER_DATABASE: user_testing
          DB_USER_PORT: 54323
          DB_USER_USERNAME: postgres
          DB_USER_PASSWORD: password
          DB_USER_SSLMODE: prefer
        run: vendor/bin/phpunit --coverage-clover tests/coverage.xml

      - if: ${{ github.event_name == 'pull_request' }}
        name: Download artifact
        uses: dawidd6/action-download-artifact@v3.0.0
        continue-on-error: true
        with:
          workflow: .github/workflows/php-tests.yml # this file
          branch: main
          name: coverage-report
          path: ${{ matrix.directory }}/tests/base

      - if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.directory }}
          path: ${{ matrix.directory }}/tests/coverage.xml

      - name: Coverage Report as Comment (Clover)
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        uses: lucassabreu/comment-coverage-clover@v0.10.4
        with:
          file: ${{ matrix.directory }}/tests/coverage.xml
          base-file: ${{ matrix.directory }}/tests/base/coverage.xml